--INNER,LEFT AND RIGHT JOINS

SELECT * FROM EMPLOYEES;    --COUNT = 111 rows
SELECT * FROM DEPARTMENTS;  --COUNT =  27 rows

select employee_id,first_name,last_name,manager_id from employees;

/* Display the first name, last name, department id and department name for each employee*/

SELECT E.FIRST_NAME,       --COUNT = 107
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME 
  FROM EMPLOYEES E 
  INNER JOIN DEPARTMENTS D
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

/* Display the first name, last name, department id and name for all employees who have 
    or not have any department */

SELECT E.FIRST_NAME,            --COUNT = 111
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT E.FIRST_NAME,            --COUNT = 111
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME 
  FROM DEPARTMENTS D
    right JOIN EMPLOYEES E
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--RIGHT JOIN

/* Display the first name, last name, department id and department names for all the departments 
   irrespectve of employees associated with them */

SELECT E.FIRST_NAME,                --COUNT = 122
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       D.LOCATION_ID
  FROM EMPLOYEES E
  RIGHT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID; 
    
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (120,130,140);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (200,210);
SELECT * FROM DEPARTMENTS;

/* Display all departments including those where does not have any employee.*/

SELECT E.FIRST_NAME,
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
  FROM DEPARTMENTS D
  LEFT JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;
    
/* Display the first name, last name, department number and name for all 
   employees who have or have not any department. */

SELECT E.FIRST_NAME,
       E.LAST_NAME,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
  FROM EMPLOYEES E
  LEFT JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
    
/* Display the first name of all employees and the first name of their 
   manager including those who does not working under any manager. */

SELECT E1.FIRST_NAME AS "EMPLOYEE_NAME",
       E2.FIRST_NAME AS "MANAGER_NAME"
  FROM EMPLOYEES E1
  LEFT JOIN EMPLOYEES E2
    ON E1.MANAGER_ID = E2.EMPLOYEE_ID; 
   
--ONE MORE EXAMPLE:

DROP TABLE PI_COMPANY;
DROP TABLE PI_COMPANY_EMPLOYEES;

CREATE TABLE PI_COMPANY
    (COMPANY_ID VARCHAR2(20) PRIMARY KEY,
     COMPANY_NAME VARCHAR2(50) NOT NULL
     );
     
CREATE TABLE PI_COMPANY_EMPLOYEES
    (EMPLOYEE_ID VARCHAR2(20) PRIMARY KEY,
     EMPLOYEE_NAME VARCHAR2(50) NOT NULL,
     HIRE_DATE DATE,
     COMPANY_ID VARCHAR2(20) REFERENCES PI_COMPANY(COMPANY_ID)
     );
     
DESC PI_COMPANY;
DESC PI_COMPANY_EMPLOYEES;

INSERT INTO PI_COMPANY VALUES ('&COMPANY_ID','&COMPANY_NAME');
SELECT * FROM PI_COMPANY;

--INSERT INTO PI_COMPANY_EMPLOYEES VALUES('&EMPLOYEE_ID','&EMPLOYEE_NAME','&to_date('DD-MON-RR')','&COMPANY_ID');
/*
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E201','SIDDESH S', TO_DATE('01-JAN-2021','DD-MON-YY'),'C001');
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E202','MOHAN KUMAR', TO_DATE('01-FEB-2021','DD-MON-YY'),'C002');
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E203','PAVANA A', TO_DATE('10-JAN-2021','DD-MON-YY'),'C003');
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E204','SUHAS G', TO_DATE('22-FEB-2021','DD-MON-YY'),'C004');
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E205','SAMARTHA', TO_DATE('01-MAR-2021','DD-MON-YY'),'C005');
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E206','MAHESH K B', NULL,NULL);
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E207','NIRANJAN K', NULL,NULL);
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E208','AKSHATHA N', NULL,NULL);
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E209','BHAVANA M', NULL,NULL);
INSERT INTO PI_COMPANY_EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,HIRE_DATE,COMPANY_ID)
VALUES('E210','DEEPAK M', NULL,NULL);
*/

SELECT * FROM PI_COMPANY;
SELECT * FROM PI_COMPANY_EMPLOYEES;

--INNER JOIN:

--DISPLAY ALL THE EMPLOYEES WHO WORKS WITH CLIENT:

SELECT COMP.COMPANY_NAME, CEMP.EMPLOYEE_NAME,CEMP.HIRE_DATE
FROM PI_COMPANY COMP INNER JOIN PI_COMPANY_EMPLOYEES CEMP
  ON COMP.COMPANY_ID = CEMP.COMPANY_ID;

--LEFT OUTER JOIN:

--DISPLAY ALL THE COMPANIES IRRESPECTIVE OF THE EMPLOYEES ASSOCIATE WITH CLIENTS:

SELECT COMP.COMPANY_NAME, CEMP.EMPLOYEE_NAME,CEMP.HIRE_DATE
FROM PI_COMPANY COMP LEFT OUTER JOIN PI_COMPANY_EMPLOYEES CEMP
  ON COMP.COMPANY_ID = CEMP.COMPANY_ID;
  
--RIGHT OUTER JOIN:

--DISPLAY ALL THE EMPLOYEES ASSOCIATE WITH US IRRESPECTIVE OF NOT WITH OUR CLIENTS:

SELECT COMP.COMPANY_NAME, CEMP.EMPLOYEE_NAME--,CEMP.HIRE_DATE
FROM PI_COMPANY COMP RIGHT OUTER JOIN PI_COMPANY_EMPLOYEES CEMP
  ON COMP.COMPANY_ID = CEMP.COMPANY_ID;
  
--FULL OUTER JOIN:

SELECT COMP.COMPANY_NAME, CEMP.EMPLOYEE_NAME,CEMP.HIRE_DATE
FROM PI_COMPANY COMP FULL OUTER JOIN PI_COMPANY_EMPLOYEES CEMP
  ON COMP.COMPANY_ID = CEMP.COMPANY_ID;
  
SELECT COMP.COMPANY_NAME, CEMP.EMPLOYEE_NAME,CEMP.HIRE_DATE
from PI_COMPANY_EMPLOYEES CEMP full outer join PI_COMPANY COMP
  ON COMP.COMPANY_ID = CEMP.COMPANY_ID;
 