SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
SELECT * FROM LOCATIONS; 
SELECT * FROM COUNTRIES; 
SELECT * FROM REGIONS; 

--INNER JOIN OR EQUI JOIN:

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;

--NORMAL JOIN

SELECT A.FIRST_NAME,B.DEPARTMENT_NAME
FROM EMPLOYEES A , DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;

--ANSI JOIN

SELECT A.FIRST_NAME,B.DEPARTMENT_NAME
FROM EMPLOYEES A INNER JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT A.FIRST_NAME, A.SALARY, B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID   --JOIN CONDITION
AND A.SALARY > 6000                       --FILTER CONDITION
ORDER BY A.SALARY;

/*--Display employee FIRST_NAME, LAST_name, his job, his dname and his location 
for all the CLERKS living in CALIFORNIA/1500 OR WASHINGTON-1700;*/
--NORMAL
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.JOB_ID LIKE '%CLERK%'
AND D.LOCATION_ID IN (1700,1500);

--ANSI
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.JOB_ID LIKE '%CLERK%'
AND D.LOCATION_ID IN (1700,1500);

--NORMAL -- with 3 tables:
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID,L.STATE_PROVINCE
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND E.JOB_ID LIKE '%CLERK%'
AND D.LOCATION_ID IN (1700,1500);

--ANSI
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID,L.STATE_PROVINCE
FROM DEPARTMENTS D 
INNER JOIN EMPLOYEES E
ON  E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.JOB_ID LIKE '%CLERK%'
AND D.LOCATION_ID IN (1700,1500);

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;

SELECT E.FIRST_NAME,E.LAST_NAME, E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID,L.STATE_PROVINCE
  FROM EMPLOYEES E 
  INNER JOIN DEPARTMENTS D
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  INNER JOIN LOCATIONS L
          ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.JOB_ID LIKE '%CLERK%'
AND L.STATE_PROVINCE IN ('California','Washington'); 


--Assignment
--1) Display employee name and his department name for the employees whose name starts with 'S' ?

--NORMAL
SELECT E.FIRST_NAME,D.DEPARTMENT_NAME
  FROM EMPLOYEES E ,DEPARTMENTS D
 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
   AND FIRST_NAME LIKE 'S%';

--MINUS TO CHECK WHETHER BOTH THE QUERIES YIELDS SAME RECORDS
--ANSI
SELECT E.FIRST_NAME,D.DEPARTMENT_NAME
  FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE FIRST_NAME LIKE 'S%';

--OUTER JOIN - Outer join = inner join + non-matching records

/*Display all the department names irrespective of any employee working in it or not. 
    If an employee is working – display his name.*/

SELECT * FROM EMPLOYEES;  --111
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES ORDER BY DEPARTMENT_ID;

SELECT * FROM DEPARTMENTS;    --27
SELECT DISTINCT DEPARTMENT_ID FROM DEPARTMENTS ORDER BY DEPARTMENT_ID;

--1         --107
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3;  

--2   RIGHT      --122   
SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3;  

--3     LEFT    --111

SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3; 

--RIGHT JOIN:

SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3;                                     ---122

--LEFT JOIN:

SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3;                                     --107

--FULL JOIN

SELECT E.FIRST_NAME,E.JOB_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID
FROM EMPLOYEES E FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 3;                                   --122


--MORE THAN 2 TABLES EXAMPLE:

/* Write a query to display the first and last name, department, city, 
   and state province for each employee. */
   
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;    

SELECT E.FIRST_NAME,
       E.LAST_NAME,
       D.DEPARTMENT_NAME,
       L.CITY,
       L.STATE_PROVINCE
  FROM EMPLOYEES E
  INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;
    
    
/*--Display employee FIRST_NAME, LAST_name, his job, his dname and his location 
for all the CLERKS living in CALIFORNIA/1500 OR WASHINGTON-1700;*/

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;

SELECT E.FIRST_NAME,E.LAST_NAME, E.JOB_ID,D.DEPARTMENT_NAME,D.LOCATION_ID,L.STATE_PROVINCE
  FROM EMPLOYEES E 
  INNER JOIN DEPARTMENTS D
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  INNER JOIN LOCATIONS L
          ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.JOB_ID LIKE '%CLERK%'
AND L.STATE_PROVINCE IN ('California','Washington');    