--VIEWS : LOGICAL TABLE ON TOP OF A BASE TABLE

SELECT * FROM EMPLOYEES;

--drop view EMPLOYEES_V1;
CREATE VIEW EMPLOYEES_V1
AS SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

SELECT * FROM EMPLOYEES_V1;

--CREATE OR REPLACE A VIEW

CREATE OR REPLACE VIEW EMPLOYEES_V1 AS 
SELECT EMPLOYEE_ID,FIRST_NAME ,LAST_NAME,SALARY, DEPARTMENT_ID
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (50,90) ;

SELECT * FROM USER_VIEWS;
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES_V1';

--DROP VIEW EMP_DETAILS_VIEW;

CREATE VIEW EMPLOYEES_V2 AS
  SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
  WHERE SALARY > 20000;
  
--DROP VIEW PI_VIEW_EMPLOYEES;
  
SELECT * FROM  EMPLOYEES_V2 ORDER BY SALARY;

--Can you update the data in an Oracle VIEW ?

SELECT * FROM PIB3_SUPPLIERS;
--Yes underlying table data can be updated by Updating a view
--drop view PIB3_SUPPLIERS_V1;
CREATE VIEW PIB3_SUPPLIERS_V1
AS SELECT * FROM PIB3_SUPPLIERS WHERE SUPPLIER_ID BETWEEN 100 AND 103; 

SELECT * FROM PIB3_SUPPLIERS_V1;

UPDATE PIB3_SUPPLIERS_V1 SET supplier_name = 'NVIDIA-2' WHERE supplier_id = 103;

SELECT * FROM PIB3_SUPPLIERS_V1;
SELECT * FROM PIB3_SUPPLIERS;

--Does the Oracle View exist if the table is dropped from the database ?

drop table PIB3_SUPPLIERS;